### ISSUE TITLE
Organisation

### ISSUE THREAD

**Issue by Chikrix** [PacktPublishing/Kotlin-Blueprints#1]
While the goals of the book are great, I have problems following it. First, prerequisites are not well set, I struggled a bit with the Javascript as I'm not primarily a JS dev, I expected something like an introduction to KotlinJs and maybe some JS, before jumping to the projects which needed Javascript, like the Geospatial messenger. Secondly, the organization was quite poor, only following the book, I don't know the package structure used, the files created or where to create a file and write the code written in the book. Which means I have to come back here frequently to check the code examples and all the stuff above. If the JS parts are not necessary, it'll be better they're not written in the book as some of us follow the book and code along.

**Comment by alexbezhan** [comment]
Hey @Chikrix I totally understand your pain. I am in the same position right now. Trying to write the code along and there is so much information missing. Need to constantly switch to this repository as well as Google a lot.

The book is unfinished and very raw.

**Comment by deepesh-packt** [comment]
Please reopen if the issue still persists.
